# generated by datamodel-codegen:
#   filename:  https://ishua.heycloudream.cn/v3/api-docs
#   timestamp: 2026-06-30T08:03:16+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class QuestionType(Enum):
    SINGLE = 'SINGLE'
    MULTI = 'MULTI'
    JUDGE = 'JUDGE'
    SHORT_ANSWER = 'SHORT_ANSWER'


class QuestionUpdateDTO(BaseModel):
    questionType: QuestionType = Field(
        ...,
        description='试题题型（接口字段为同名 string，取值见枚举）',
        examples=['SINGLE'],
    )
    stem: constr(min_length=0, max_length=8192) = Field(..., description='题干纯文本')
    optionsJson: constr(min_length=0, max_length=65535) = Field(
        ...,
        description='选项 JSON 数组字符串，如 ["选项A","选项B"]',
        examples=['["TCP","UDP","IP","ICMP"]'],
    )
    answerJson: constr(min_length=0, max_length=4096) = Field(
        ...,
        description='答案 JSON 数组字符串，如 ["A"]、["A","C"]；判断题 ["T"] 或 ["F"]',
        examples=['["A","B"]'],
    )
    analysis: constr(min_length=0, max_length=8192) | None = Field(
        None, description='题目解析，可选'
    )
    sortNo: conint(ge=1) | None = Field(
        None, description='题库内排序号，可选；不传则由服务端默认'
    )


class QuestionBankUpdateDTO(BaseModel):
    title: constr(min_length=0, max_length=200) = Field(
        ..., description='题库名称', examples=['2026计算机网络期末必刷题']
    )
    description: constr(min_length=0, max_length=2000) | None = Field(
        None, description='题库描述', examples=['面向期末周的重点题型整理']
    )
    isPublic: conint(ge=0, le=1) = Field(
        ..., description='是否公开：0-否，1-是', examples=[1]
    )


class BankNodeUpdateDTO(BaseModel):
    title: constr(min_length=0, max_length=200) = Field(..., description='节点标题')
    description: constr(min_length=0, max_length=2000) | None = Field(
        None, description='节点描述'
    )
    isPublic: conint(ge=0, le=1) | None = Field(
        None, description='是否公开：0-否，1-是（LEAF 有效）'
    )
    sortNo: int | None = Field(None, description='同级排序号')


class AdminUserRoleUpdateDTO(BaseModel):
    role: str = Field(
        ..., description='目标角色，仅允许 USER 或 PREMIUM', examples=['PREMIUM']
    )


class UserRegisterDTO(BaseModel):
    username: constr(min_length=3, max_length=64) = Field(
        ..., description='登录账号', examples=['zhangsan']
    )
    password: constr(min_length=6, max_length=64) = Field(
        ..., description='登录密码', examples=['123456']
    )
    email: constr(min_length=0, max_length=254) = Field(
        ..., description='邮箱', examples=['zhangsan@example.com']
    )
    code: constr(pattern=r'\d{6}') = Field(
        ..., description='邮箱验证码', examples=['123456']
    )
    nickname: constr(min_length=0, max_length=64) | None = Field(
        None, description='昵称（选填）', examples=['张三']
    )


class UserRegisterEmailCodeDTO(BaseModel):
    email: constr(min_length=0, max_length=254) = Field(
        ..., description='邮箱', examples=['zhangsan@example.com']
    )
    turnstileToken: constr(min_length=0, max_length=2048) = Field(
        ...,
        description='Cloudflare Turnstile 令牌',
        examples=['0.abcdefghijklmnopqrstuvwxyz'],
    )


class UserLoginDTO(BaseModel):
    username: str = Field(..., description='登录账号', examples=['zhangsan'])
    password: str = Field(..., description='登录密码', examples=['123456'])


class UserLoginVO(BaseModel):
    token: str | None = Field(
        None, description='JWT 访问令牌', examples=['eyJhbGciOiJIUzI1NiJ9...']
    )
    userId: int | None = Field(None, description='用户 ID', examples=[1])
    username: str | None = Field(None, description='登录账号', examples=['zhangsan'])
    nickname: str | None = Field(None, description='昵称', examples=['张三'])
    role: str | None = Field(
        None,
        description='用户角色：USER-普通用户，PREMIUM-高级用户，ADMIN-管理员',
        examples=['USER'],
    )


class QuestionBankCreateDTO(BaseModel):
    title: constr(min_length=0, max_length=200) = Field(
        ..., description='题库名称', examples=['2026计算机网络期末必刷题']
    )
    description: constr(min_length=0, max_length=2000) | None = Field(
        None, description='题库描述', examples=['面向期末周的重点题型整理']
    )
    isPublic: conint(ge=0, le=1) = Field(
        ..., description='是否公开：0-否，1-是', examples=[1]
    )


class QuestionPreviewVO(BaseModel):
    questionType: QuestionType | None = Field(
        None,
        description='试题题型（接口字段为同名 string，取值见枚举）',
        examples=['SINGLE'],
    )
    stem: str | None = Field(
        None,
        description='题干文本',
        examples=['理想气体状态方程 PV=nRT 中，R 的数值是？'],
    )
    options: list[str] | None = Field(
        None, description='选项文案列表（判断题固定 ["正确","错误"]）'
    )
    answer: list[str] | None = Field(
        None, description='正确答案：单选 ["B"]；多选 ["A","C"]；判断题 ["T"] 或 ["F"]'
    )
    analysis: str | None = Field(None, description='题目解析')
    answerSource: str | None = Field(
        None,
        description='答案来源：ORIGINAL/MISSING/AI_GENERATED',
        examples=['ORIGINAL'],
    )
    answerConfidence: str | None = Field(
        None, description='答案置信度：HIGH/MEDIUM/LOW（仅 AI 解答写入）'
    )


class AnswerSubmitDTO(BaseModel):
    userAnswer: list[str] = Field(
        ..., description='用户选择的答案列表。单选/多选传大写字母；判断题传 T/F'
    )


class AnswerSubmitResultVO(BaseModel):
    questionId: int | None = Field(None, description='试题 ID', examples=[50001])
    correct: bool | None = Field(
        None, description='是否正确；主观题时为 null', examples=[True]
    )
    needsManualGrading: bool | None = Field(
        None, description='是否需要人工判分（主观题或未知题型）', examples=[False]
    )
    answerJson: str | None = Field(
        None,
        description='标准答案 JSON 数组字符串，如 ["A"]、["T"]',
        examples=['["A","C"]'],
    )
    analysis: str | None = Field(None, description='题目解析（可为空）')


class BankNodeCreateDTO(BaseModel):
    parentId: int | None = Field(
        None, description='父节点 ID，NULL 表示根节点', examples=[1]
    )
    nodeKind: constr(pattern=r'FOLDER|LEAF') = Field(
        ..., description='节点类型：FOLDER-文件夹，LEAF-可挂题题库', examples=['LEAF']
    )
    title: constr(min_length=0, max_length=200) = Field(
        ..., description='节点标题', examples=['高等数学']
    )
    description: constr(min_length=0, max_length=2000) | None = Field(
        None, description='节点描述'
    )
    isPublic: conint(ge=0, le=1) | None = Field(
        None, description='是否公开：0-否，1-是（LEAF 有效）', examples=[0]
    )
    sortNo: int | None = Field(None, description='同级排序号，越小越前', examples=[0])


class AiAnswerCreateDTO(BaseModel):
    questionIndices: list[int] | None = Field(
        None,
        description='指定待解答题目在 preview_json 中的下标列表（0-based）。\n与 filter 二选一；同时给出时以此为准。\n',
        examples=[[0, 3, 5]],
    )
    filter: str | None = Field(
        None,
        description='过滤模式：MISSING 表示自动筛选所有 answerSource=MISSING 且题型为 SINGLE/MULTI/JUDGE 的题目。\n与 questionIndices 二选一。\n',
        examples=['MISSING'],
    )


class AiAnswerSubmitVO(BaseModel):
    answerTaskId: str | None = Field(
        None,
        description='解答任务 ID（UUID）',
        examples=['a1b2c3d4e5f67890abcdef1234567890'],
    )
    parentTaskId: str | None = Field(None, description='关联的 ai_import_task.task_id')
    status: str | None = Field(None, description='初始状态', examples=['SUBMITTED'])
    questionCount: int | None = Field(None, description='待解答题目数', examples=[20])


class AiImportSubmitVO(BaseModel):
    taskId: str | None = Field(
        None,
        description='任务 ID（UUID）',
        examples=['a1b2c3d4e5f67890abcdef1234567890'],
    )
    status: str | None = Field(None, description='初始状态', examples=['SUBMITTED'])


class AdminAiImportCleanupDTO(BaseModel):
    olderThanDays: conint(ge=1, le=365) | None = Field(
        None,
        description='parsed_at 早于「当前时间 − olderThanDays 天」的 PARSED 任务纳入清理范围；不传时服务端默认 7（见配置 ishua.ai-import.cleanup-default-older-than-days）',
        examples=[7],
    )
    bankId: int | None = Field(
        None, description='可选：仅清理指定题库下的任务', examples=[1001]
    )
    userId: int | None = Field(
        None, description='可选：仅清理指定用户提交的任务', examples=[1]
    )
    dryRun: bool | None = Field(
        True,
        description='是否仅预检：true 只返回 matchedCount 与 sampleTaskIds，不写库；false 执行 EXPIRED 标记与 Redis 清理。不传时视为 true',
        examples=[True],
    )
    deleteFiles: bool | None = Field(
        False,
        description='实清（dryRun=false）时是否删除 file_url 指向的上传文件；默认 false，仅清任务与缓存',
        examples=[False],
    )
    maxBatch: conint(ge=1, le=1000) | None = Field(
        200,
        description='单次请求最多处理的任务条数，防止长事务；不传时默认 200',
        examples=[200],
    )


class AdminAiImportCleanupResultVO(BaseModel):
    dryRun: bool | None = Field(
        None, description='本次请求是否为预检（与请求体 dryRun 一致）', examples=[True]
    )
    matchedCount: int | None = Field(
        None,
        description='符合清理条件（PARSED 且 parsed_at 早于阈值）的任务总数，可能大于 processedCount',
        examples=[12],
    )
    processedCount: int | None = Field(
        None,
        description='实际处理条数：dryRun=true 时为 0；dryRun=false 时为成功标记 EXPIRED 的条数',
        examples=[0],
    )
    sampleTaskIds: list[str] | None = Field(
        None, description='样例 taskId 列表（最多 10 条），便于运维核对后再实清'
    )
    message: str | None = Field(
        None,
        description='结果说明，如「dryRun：未执行写操作」或「已清理 N 个长时间未确认任务」',
        examples=['dryRun：未执行写操作'],
    )


class BankNodeMoveDTO(BaseModel):
    newParentId: int | None = Field(
        None, description='新父节点 ID，NULL 表示移到根', examples=[5]
    )
    newSortNo: conint(ge=0) | None = Field(
        None, description='在新父节点下的排序号', examples=[0]
    )


class WrongQuestionVO(BaseModel):
    id: int | None = Field(
        None, description='错题本记录 ID（用于移除操作）', examples=[1]
    )
    questionId: int | None = Field(None, description='试题 ID', examples=[50001])
    questionBankId: int | None = Field(None, description='所属题库 ID', examples=[1001])
    questionType: QuestionType | None = Field(
        None,
        description='试题题型（接口字段为同名 string，取值见枚举）',
        examples=['SINGLE'],
    )
    stem: str | None = Field(None, description='题干纯文本')
    optionsJson: str | None = Field(
        None, description='选项 JSON 数组字符串', examples=['["TCP","UDP","IP","ICMP"]']
    )
    wrongCount: int | None = Field(None, description='累计做错次数', examples=[3])
    lastWrongTime: AwareDatetime | None = Field(None, description='最近一次做错时间')


class PracticeQuestionVO(BaseModel):
    id: int | None = Field(None, description='试题主键', examples=[50001])
    questionBankId: int | None = Field(None, description='所属题库 ID', examples=[1001])
    questionType: QuestionType | None = Field(
        None,
        description='试题题型（接口字段为同名 string，取值见枚举）',
        examples=['SINGLE'],
    )
    stem: str | None = Field(None, description='题干纯文本')
    optionsJson: str | None = Field(
        None,
        description='选项 JSON 数组字符串，如 ["TCP","UDP"]；简答题（SHORT_ANSWER）为 []',
        examples=['["TCP","UDP","IP","ICMP"]'],
    )
    sortNo: int | None = Field(None, description='题库内排序号', examples=[1])


class UserMeVO(BaseModel):
    userId: int | None = Field(None, description='用户 ID', examples=[1])
    username: str | None = Field(None, description='登录账号', examples=['zhangsan'])
    nickname: str | None = Field(None, description='昵称', examples=['张三'])
    role: str | None = Field(
        None,
        description='用户角色：USER-普通用户，PREMIUM-高级用户，ADMIN-管理员',
        examples=['USER'],
    )


class QuestionVO(BaseModel):
    id: int | None = Field(None, description='试题主键', examples=[50001])
    questionBankId: int | None = Field(None, description='所属题库 ID', examples=[1001])
    questionType: QuestionType | None = Field(
        None,
        description='试题题型（接口字段为同名 string，取值见枚举）',
        examples=['SINGLE'],
    )
    stem: str | None = Field(None, description='题干纯文本')
    optionsJson: str | None = Field(
        None,
        description='选项 JSON 数组字符串。单选/多选为选项文案列表；简答题（SHORT_ANSWER）为 []',
        examples=['["8.31 J/(mol·K)","8.31 kJ/(mol·K)","0.0821 L·atm/(mol·K)"]'],
    )
    answerJson: str | None = Field(
        None,
        description='答案 JSON 数组字符串。单选/多选为字母；判断题为 ["T"]/["F"]；简答题为文本要点数组',
        examples=['["C"]'],
    )
    answerSource: str | None = Field(
        None,
        description='答案来源：ORIGINAL/MISSING/AI_GENERATED',
        examples=['ORIGINAL'],
    )
    answerConfidence: str | None = Field(
        None, description='答案置信度：HIGH/MEDIUM/LOW（仅 AI 解答写入）'
    )
    analysis: str | None = Field(None, description='题目解析')
    sortNo: int | None = Field(None, description='题库内排序号', examples=[1])
    createTime: AwareDatetime | None = Field(None, description='创建时间')
    updateTime: AwareDatetime | None = Field(None, description='更新时间')


class QuestionBankVO(BaseModel):
    id: int | None = Field(None, description='题库主键', examples=[1001])
    userId: int | None = Field(None, description='创建者用户 ID', examples=[20])
    title: str | None = Field(
        None, description='题库名称', examples=['2026计算机网络期末必刷题']
    )
    description: str | None = Field(None, description='题库描述')
    isPublic: int | None = Field(
        None,
        description='是否公开：0=私有，1=公开（公开题库可出现在大厅与热点刷题接口）',
        examples=[1],
    )
    createTime: AwareDatetime | None = Field(None, description='创建时间')
    updateTime: AwareDatetime | None = Field(None, description='更新时间')


class QuestionBankDetailBundleVO(BaseModel):
    bank: QuestionBankVO | None = None
    questions: list[QuestionVO] | None = Field(
        None, description='该题库下全部试题（按 sortNo 有序；含答案与解析）'
    )


class PracticeReferenceAnswerVO(BaseModel):
    questionId: int | None = Field(None, description='试题 ID', examples=[50001])
    questionType: QuestionType | None = Field(
        None,
        description='试题题型（接口字段为同名 string，取值见枚举）',
        examples=['SHORT_ANSWER'],
    )
    answerJson: str | None = Field(
        None,
        description='参考答案 JSON 数组字符串，每项为一个要点或段落，如 ["要点一","要点二"]',
        examples=['["客户端发 SYN，服务端回 SYN+ACK，客户端再发 ACK"]'],
    )
    analysis: str | None = Field(None, description='题目解析（可为空）')


class BankNodeVO(BaseModel):
    id: int | None = Field(None, description='节点 ID')
    userId: int | None = Field(None, description='所有者用户 ID')
    parentId: int | None = Field(None, description='父节点 ID，根节点为 null')
    nodeKind: str | None = Field(None, description='节点类型：FOLDER | LEAF')
    title: str | None = Field(None, description='标题')
    description: str | None = Field(None, description='描述')
    isPublic: int | None = Field(None, description='是否公开：0-否，1-是')
    sortNo: int | None = Field(None, description='同级排序号')
    questionCount: int | None = Field(None, description='题目数量（LEAF 冗余字段）')
    childCount: int | None = Field(None, description='直接子节点数量')
    descendantLeafCount: int | None = Field(None, description='子树内 LEAF 节点总数')
    hasPublicDescendant: bool | None = Field(None, description='子树是否含公开 LEAF')
    createTime: AwareDatetime | None = Field(None, description='创建时间')
    updateTime: AwareDatetime | None = Field(None, description='更新时间')


class AiImportTaskSummaryVO(BaseModel):
    taskId: str | None = Field(
        None,
        description='业务任务 ID（UUID），与轮询、batch 接口一致',
        examples=['a1b2c3d4e5f67890abcdef1234567890'],
    )
    bankId: int | None = Field(None, description='目标题库 ID', examples=[1001])
    fileName: str | None = Field(
        None, description='用户上传时的原始文件名', examples=['期末复习.pdf']
    )
    status: str | None = Field(
        None,
        description='任务状态：SUBMITTED、PROCESSING、PARSED、IMPORTING、IMPORTED、FAILED、EXPIRED。\nPARSED 表示可进入预览确认；EXPIRED 表示已过期清理，需重新 submit。\n',
        examples=['PARSED'],
    )
    message: str | None = Field(
        None,
        description='FAILED/EXPIRED 时的原因摘要，或成功态业务说明；可为空',
        examples=['解析完成，待确认导入'],
    )
    questionCount: int | None = Field(
        None, description='解析出的题目数量；PARSED 及之后有意义', examples=[42]
    )
    submittedAt: AwareDatetime | None = Field(None, description='任务提交时间')
    parsedAt: AwareDatetime | None = Field(
        None, description='进入 PARSED 的时间；未解析完成时为 null'
    )
    importedAt: AwareDatetime | None = Field(
        None, description='确认 batch 落库完成时间；未导入时为 null'
    )
    expiredAt: AwareDatetime | None = Field(
        None, description='被管理端清理为 EXPIRED 的时间；未过期时为 null'
    )
    questions: list[QuestionPreviewVO] | None = Field(
        None,
        description='预览题目列表；仅查询参数 includePreview=true 且本条 status=PARSED 时非空',
    )


class AiImportTaskPipelineMetricsVO(BaseModel):
    mineruMs: int | None = Field(
        None, description='MinerU 文档解析耗时（毫秒）', examples=[120000]
    )
    llmMs: int | None = Field(
        None, description='LLM 题目抽取耗时（毫秒）', examples=[8500]
    )
    pipelineMs: int | None = Field(
        None, description='MinerU + LLM 总耗时（毫秒）', examples=[128500]
    )


class AiImportTaskStatusVO(BaseModel):
    taskId: str | None = Field(None, description='任务 ID（UUID）')
    status: str | None = Field(
        None,
        description='任务状态：SUBMITTED（已入队）→ PROCESSING（解析中）→ PARSED（可预览）→\nIMPORTING（落库中，可选）→ IMPORTED（完成）、FAILED（失败）或 EXPIRED（长时间未确认已过期）\n',
        examples=['PARSED'],
    )
    message: str | None = Field(
        None, description='FAILED/EXPIRED 时的错误摘要，或业务说明；成功流转中常为空'
    )
    totalCount: int | None = Field(
        None,
        description='解析出的题目总数；status=PARSED 时通常等于 questions.length',
        examples=[42],
    )
    questions: list[QuestionPreviewVO] | None = Field(
        None,
        description='预览题目列表。status=PARSED 时返回（优先 MySQL preview_json，其次 Redis result）。\n终态 IMPORTED/FAILED/EXPIRED 时不返回或为空。\n',
    )
    metrics: AiImportTaskPipelineMetricsVO | None = None


class AiAnswerMetricsVO(BaseModel):
    llmMs: int | None = Field(None, description='LLM 总耗时（毫秒）', examples=[45000])
    totalCalls: int | None = Field(
        None, description='总 LLM 调用次数（分片×投票）', examples=[6]
    )


class AiAnswerTaskStatusVO(BaseModel):
    answerTaskId: str | None = Field(None, description='解答任务 ID（UUID）')
    status: str | None = Field(
        None,
        description='任务状态：SUBMITTED（已入队）→ PROCESSING（解答中）→\nANSWERED（全部成功）/ PARTIAL（部分失败）/ FAILED（整体失败）→ IMPORTED（已入库）\n',
        examples=['ANSWERED'],
    )
    message: str | None = Field(
        None, description='FAILED/PARTIAL 时的错误摘要，或业务说明'
    )
    totalCount: int | None = Field(None, description='待解答题目总数', examples=[20])
    answeredCount: int | None = Field(None, description='成功解答数', examples=[18])
    questions: list[QuestionPreviewVO] | None = Field(
        None,
        description='解答结果列表。status=ANSWERED/PARTIAL 时返回。\n每项为 QuestionPreviewVO，含 answerSource=AI_GENERATED 与 answerConfidence。\n',
    )
    metrics: AiAnswerMetricsVO | None = None


class AdminUserVO(BaseModel):
    userId: int | None = Field(None, description='用户 ID', examples=[1])
    username: str | None = Field(None, description='登录账号', examples=['zhangsan'])
    nickname: str | None = Field(None, description='昵称', examples=['张三'])
    role: str | None = Field(
        None,
        description='用户角色：USER-普通用户，PREMIUM-高级用户，ADMIN-管理员',
        examples=['USER'],
    )
    createTime: AwareDatetime | None = Field(None, description='创建时间')
    updateTime: AwareDatetime | None = Field(None, description='更新时间')


class AdminAiImportStatusStatVO(BaseModel):
    status: str | None = Field(None, description='任务状态', examples=['IMPORTED'])
    count: int | None = Field(None, description='该状态任务数', examples=[42])
    avgParseSeconds: float | None = Field(
        None,
        description='该状态下任务的平均流水线耗时（秒，pipeline_duration_ms）；无实测数据时不参与计算',
        examples=[18.5],
    )


class BatchImportRequestDTO(BaseModel):
    taskId: str = Field(
        ...,
        description='AI 导入任务 ID（UUID），来自 submit 响应、GET /ai-import/tasks 或 GET .../tasks/{taskId}/status',
        examples=['a1b2c3d4e5f67890abcdef1234567890'],
    )
    questions: list[QuestionPreviewVO] = Field(
        ...,
        description='经用户预览页确认/编辑后的题目列表；结构与轮询接口 QuestionPreviewVO 一致',
    )


class AdminAiImportStatsVO(BaseModel):
    periodDays: int | None = Field(
        None, description='统计窗口天数（与请求参数 days 一致）', examples=[30]
    )
    periodStart: AwareDatetime | None = Field(
        None, description='统计起始时间（含）：submitted_at >= periodStart'
    )
    periodEnd: AwareDatetime | None = Field(
        None, description='统计截止时间（不含，通常为接口调用时刻）'
    )
    totalTasks: int | None = Field(
        None, description='窗口内提交的任务总数', examples=[120]
    )
    statusStats: list[AdminAiImportStatusStatVO] | None = Field(
        None, description='各状态任务数及该状态下的平均解析耗时'
    )
    dailyAvgSubmitCount: float | None = Field(
        None, description='日均提交量（totalTasks / periodDays）', examples=[4.0]
    )
    avgPipelineSeconds: float | None = Field(
        None,
        description='Worker 实测流水线平均耗时（秒，MinerU + LLM）；无 pipeline_duration_ms 的历史任务不参与',
        examples=[128.5],
    )
    avgMineruSeconds: float | None = Field(
        None, description='MinerU 平均耗时（秒）', examples=[120.0]
    )
    avgLlmSeconds: float | None = Field(
        None, description='LLM 平均耗时（秒）', examples=[8.5]
    )
    avgParseSeconds: float | None = Field(
        None, description='同 avgPipelineSeconds，保留兼容', examples=[128.5]
    )
    avgQuestionCount: float | None = Field(
        None,
        description='平均解析题目数（question_count 非空记录的平均值）',
        examples=[15.6],
    )
    failureRate: float | None = Field(
        None,
        description='失败率（status=FAILED 占 totalTasks 的比例，0~1，如 0.08 表示 8%）',
        examples=[0.08],
    )
